# Generated by Django 2.2 on 2019-05-28 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 17, 58, 40, 366924)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notetag',
            name='color',
            field=models.CharField(default='ffffff', max_length=6),
            preserve_default=False,
        ),
    ]
