# Generated by Django 2.2 on 2019-08-02 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190802_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='notes.NoteTag'),
        ),
        migrations.RemoveField(
            model_name='note',
            name='types',
        ),
        migrations.AddField(
            model_name='note',
            name='types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.NoteType'),
        ),
        migrations.AlterField(
            model_name='notetype',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
