# Generated by Django 2.2 on 2019-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20190802_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetag',
            name='color',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
