# Generated by Django 2.2 on 2019-08-02 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190802_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='types',
            new_name='type',
        ),
    ]
