# Generated by Django 2.2 on 2019-09-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='type',
        ),
        migrations.DeleteModel(
            name='NoteType',
        ),
    ]
