# Generated by Django 2.2 on 2019-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20191001_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
