# Generated by Django 2.2.6 on 2019-10-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_note_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
